# This is a basic workflow to help you get started with Actions

name: download random giphy
on:
  schedule:
    - cron: "0 0 * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  curl:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      name: curl from ubuntu
      env:
        GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
      run: |
        curl https://httpbin.org/get?api_key=${GIPHY_API_KEY}
        curl -o giphyData.json 'https://api.giphy.com/v1/gifs/random?api_key=${GIPHY_API_KEY}&limit=1'
        cat giphyData.json
        giphyUrl=$(jq '.data.images.original.url' giphyData.json)
        curl -I $(giphyUrl)
#    - name: get data of random giphy
#      id: downloadData
#      uses: wei/curl@master
#      env:
#        GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
#      with:
#        args: "https://api.giphy.com/v1/gifs/random?api_key=${GIPHY_API_KEY}&limit=1"
#    - name: get random giphy url
#      id: giphyUrl
#      uses: sergeysova/jq-action@v2
#      with:
#        cmd: 'echo ${{ steps.download.outputs.value }}'
        
        
        
        
        
