# This is a basic workflow to help you get started with Actions

name: download random stuffs
on:
  schedule:
    - cron: "0 0 * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  provide_random_gif:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - shell: bash
      name: download image
      env:
        GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
      run: | 
        curl -o giphyData.json "https://api.giphy.com/v1/gifs/random?api_key=${GIPHY_API_KEY}&tag=fail&limit=1"
        giphyUrl=$(jq '.data.images.original.url' giphyData.json | sed "s/\"//g")
        curl -o random.gif ${giphyUrl}
    - shell: bash
      name: download bucketlist
      env:
        API_NINJAS_API_KEY: ${{ secrets.API_NINJAS_API_KEY }}
      run: | 
        echo -en "<h1 style=\"text-align: center\">$(curl -s -H 'X-Api-Key: ${API_NINJAS_API_KEY}' 'https://api.api-ninjas.com/v1/bucketlist' | jq -r '.item')</h1>" > bucketlist.html
        echo -en "<h1 style=\"text-align: center\">$(curl -s -H 'X-Api-Key: ${API_NINJAS_API_KEY}' 'https://api.api-ninjas.com/v1/chucknorris' | jq -r '.joke')</h1>" > chucknorris.html
        echo -en "<h1 style=\"text-align: center\">$(curl -s -H 'X-Api-Key: ${API_NINJAS_API_KEY}' 'https://api.api-ninjas.com/v1/dadjokes' | jq -r '.[0].joke')</h1>" > dadjokes.html
        echo -en "<h1 style=\"text-align: center\">$(curl -s -H 'X-Api-Key: ${API_NINJAS_API_KEY}' 'https://api.api-ninjas.com/v1/facts' | jq -r '.[0].fact')</h1>" > facts.html
        echo -en "<h1 style=\"text-align: center\">$(curl -s -H 'X-Api-Key: ${API_NINJAS_API_KEY}' 'https://api.api-ninjas.com/v1/jokes' | jq -r '.[0].joke')</h1>" > jokes.html
        echo -en "<h1 style=\"text-align: center\">$(curl -s -H 'X-Api-Key: ${API_NINJAS_API_KEY}' 'https://api.api-ninjas.com/v1/riddles' | jq -r '.[0] | .question, .answer')</h1>" > riddles.html
        echo -en "<h1 style=\"text-align: center\">$(curl -s -H 'X-Api-Key: ${API_NINJAS_API_KEY}' 'https://api.api-ninjas.com/v1/passwordgenerator?length=64' | jq -r '.random_password')</h1>" > passwordgenerator.html
        echo -en "<h1 style=\"text-align: center\">$(curl -s -H 'X-Api-Key: ${API_NINJAS_API_KEY}' 'https://api.api-ninjas.com/v1/babynames?gender=neutral' | jq -r '.[0]')</h1>" > babynames.html





    - shell: bash
      name: push everything to git
      run: | 
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add -A
        git commit -m 'deployment'
        git push origin main:gh-pages -f        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.PUSH_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0
