# This is a basic workflow to help you get started with Actions

name: download random giphy
on:
  schedule:
    - cron: "0 0 * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - shell: bash
      name: curl from ubuntu
      env:
        GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
      run: |
        curl -o giphyData.json "https://api.giphy.com/v1/gifs/random?api_key=${GIPHY_API_KEY}&limit=1"
        giphyUrl=$(jq '.data.images.original.url' giphyData.json | sed "s/\"//g")
        echo ${giphyUrl}
        curl -o random.gif ${giphyUrl}
        #git config --global user.email "deployment@example.com"
        #git config --global user.name "deployment"
        #git add -A
        #git commit -m 'deployment'
        #echo ${{ secrets.GITHUB_TOKEN }} |  sed 's/.\{1\}/& /g'
        #git push -f https://YoshiMan:${{ secrets.GITHUB_TOKEN }}@github.com/YoshiMan/random-giphy-every-day.git main:gh-pages
        git config --global user.name 'Your Name'
        git config --global user.email 'your-username@users.noreply.github.com'
        git commit -am "deployment"
        git push

#    - name: get data of random giphy
#      id: downloadData
#      uses: wei/curl@master
#      env:
#        GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
#      with:
#        args: "https://api.giphy.com/v1/gifs/random?api_key=${GIPHY_API_KEY}&limit=1"
#    - name: get random giphy url
#      id: giphyUrl
#      uses: sergeysova/jq-action@v2
#      with:
#        cmd: 'echo ${{ steps.download.outputs.value }}'
        
        
        
        
        
