# This is a basic workflow to help you get started with Actions

name: download random giphy
on:
  schedule:
    - cron: "0 0 * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - shell: bash
      name: curl from ubuntu
      env:
        GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
        PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
      run: | 
        curl -o giphyData.json "https://api.giphy.com/v1/gifs/random?api_key=${GIPHY_API_KEY}&limit=1"
        giphyUrl=$(jq '.data.images.original.url' giphyData.json | sed "s/\"//g")
        curl -o random.gif ${giphyUrl}
        
        git config --global user.email "Your Name"
        git config --global user.name "your-username@users.noreply.github."
        git init
        git add -A
        git commit -m 'deployment'
        git push -f "https://YoshiMan:$PUSH_TOKEN@github.com/YoshiMan/random-giphy-every-day.git" main:gh-pages
  
