# This is a basic workflow to help you get started with Actions

name: download random giphy
on:
  schedule:
    - cron: "0 0 * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      env:
        GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
      with:
        args: "https://httpbin.org/get?api_key=${GIPHY_API_KEY}"
